### PR TITLE
Update jquery.draghandler.js

### PR DESCRIPTION
**Pull request by lifeiscontent**
Optimize the codes

This has a breaking change, the context of the function is no longer `$this`, it's just plain `this` which is 100% expected from jQuery plugins.

### CODE REVIEW

**Comment by lifeiscontent** [comment]
@monteiz should I close this PR?

**Comment by monteiz** [comment]
Merged, thanks.

**Comment by lifeiscontent** [comment]
@monteiz you didn't click the merge button...

**Comment by monteiz** [comment]
Ops. Now it should be ok.

**Pull request merged**
